const MARGIN_TABLE = {
	10: 4,
	20: 3,
	40: 1,
	60: 1
}

const PIXEL_FIX = 0.5
const OUTTER_MARGIN = 2
const VOL_HEIGHT = 66
const FONT_SIZE = 20
const WIN_COLOR = '#e63232'
const LOSS_COLOR = '#55a500'
const STROKE_COLOR = '#d8d8d8'
const DASH_COLOR = '#999999'
const BOTTOM_TEXT_HEIGHT = 20
const TEXT_COLOR = '#0287fe'

module.exports = {
	MARGIN_TABLE,
	OUTTER_MARGIN,
	VOL_HEIGHT,
	FONT_SIZE,
	PIXEL_FIX,
	WIN_COLOR,
	LOSS_COLOR,
	STROKE_COLOR,
	DASH_COLOR,
	BOTTOM_TEXT_HEIGHT,
	TEXT_COLOR
}